<?php

namespace LorPHP\Helpers;

class FileGenerator
{
    public static function generateFileHeader(): string
    {
        $date = date('Y-m-d H:i:s');
        return <<<PHP
/**
 * This file is auto-generated by LorPHP.
 * Generated on: {$date}
 * 
 * WARNING: Do not edit this file manually.
 * Any changes will be overwritten when the file is regenerated.
 */

PHP;
    }

    public static function generateSaveMethod(): string
    {
        return <<<PHP

    public function save(): bool {
        return parent::save();
    }
PHP;
    }
}
