<?php
/**
 * This file is auto-generated by LorPHP.
 * Do not edit this file manually as your changes will be overwritten.
 */
namespace LorPHP\Database\Migrations;

use LorPHP\Core\Migration;
use LorPHP\Core\Schema;

class CreateRateLimitTable extends Migration
{
    public function up()
    {
        $this->createTable('ratelimits', function(Schema $table) {
            $table->string('id');
            $table->timestamp('created_at');
            $table->timestamp('updated_at');
            $table->boolean('is_active');
            $table->string('modified_by')->nullable();
            $table->string('ip_address');
            $table->string('endpoint');
            $table->integer('requests');
            $table->datetime('window_start');
            $table->integer('window_duration');
            $table->integer('max_requests');
            $table->string('user_id')->nullable();
            $table->boolean('blocked');

        });
    }

    public function down()
    {
        $this->dropTable('ratelimits');
    }
}
