<?php

/**
 * This file is auto-generated by LorPHP.
 * Generated on: 2025-05-22 01:28:30
 * 
 * WARNING: Do not edit this file manually.
 * Any changes will be overwritten when the file is regenerated.
 */
namespace LorPHP\Database\Migrations;

use LorPHP\Core\Migration;
use LorPHP\Core\Schema;

class CreateOrganizationTable extends Migration
{
    public function up()
    {
        $this->createTable('organizations', function(Schema $table) {
            $table->uuid();
            $table->timestamp('createdAt');
            $table->timestamp('updatedAt');
            $table->boolean('isActive');
            $table->string('modifiedBy')->nullable();
            $table->string('name');

        });
    }

    public function down()
    {
        $this->dropTable('organizations');
    }
}
