<?php
/**
 * This file is auto-generated by LorPHP.
 * Do not edit this file manually as your changes will be overwritten.
 */
namespace LorPHP\Database\Migrations;

use LorPHP\Core\Migration;
use LorPHP\Core\Schema;

class CreateUserTable extends Migration
{
    public function up()
    {
        $this->createTable('users', function(Schema $table) {
            $table->string('id');
            $table->timestamp('created_at');
            $table->timestamp('updated_at');
            $table->boolean('is_active');
            $table->string('modified_by')->nullable();
            $table->string('name');
            $table->string('email');
            $table->unique('email');
            $table->string('password');
            $table->string('role')->nullable();

        });
    }

    public function down()
    {
        $this->dropTable('users');
    }
}
