<?php

/**
 * This file is auto-generated by LorPHP.
 * Generated on: 2025-05-22 01:19:26
 * 
 * WARNING: Do not edit this file manually.
 * Any changes will be overwritten when the file is regenerated.
 */
namespace LorPHP\Database\Migrations;

use LorPHP\Core\Migration;
use LorPHP\Core\Schema;

class CreateContactTable extends Migration
{
    public function up()
    {
        $this->createTable('contacts', function(Schema $table) {
            $table->uuid();
            $table->timestamp('createdAt');
            $table->timestamp('updatedAt');
            $table->boolean('isActive');
            $table->string('modifiedBy')->nullable();
            $table->string('name');
            $table->string('email');
            $table->string('clientId');

        });
    }

    public function down()
    {
        $this->dropTable('contacts');
    }
}
