<?php
/**
 * This file is auto-generated by LorPHP.
 * Do not edit this file manually as your changes will be overwritten.
 */
namespace LorPHP\Database\Migrations;

use LorPHP\Core\Migration;
use LorPHP\Core\Schema;

class CreateUserTable extends Migration
{
    public function up()
    {
        $this->createTable('users', function(Schema $table) {
            $table->uuid();
            $table->timestamp('createdAt');
            $table->timestamp('updatedAt');
            $table->boolean('isActive');
            $table->string('modifiedBy')->nullable();
            $table->string('name');
            $table->string('email')->unique();
            $table->string('password');
            $table->string('role')->nullable();

        });
    }

    public function down()
    {
        $this->dropTable('users');
    }
}
