<?php

/**
 * This file is auto-generated by LorPHP.
 * Generated on: 2025-06-05 14:48:23
 * 
 * WARNING: Do not edit this file manually.
 * Any changes will be overwritten when the file is regenerated.
 */
namespace LorPHP\Interfaces;

/**
 * Interface ClientInterface
 * Represents a client
 *
 * @property String $id Unique identifier for the record
 * @property DateTime $created_at Timestamp of when the record was created
 * @property DateTime $updated_at Timestamp of when the record was last updated
 * @property Boolean $is_active Whether the record is active
 * @property String|null $modified_by Identifier of the user who last modified the record
 * @property String $name Name
 * @property String $email Email
 * @property String $organizationId OrganizationId
 * @property Organization $organization Organization
 * @property Contact $contacts Contacts for this client
 * @property Package $packages Packages associated with this client
 */
interface ClientInterface
{
    /**
     * Get the id
     * @return String
     */
    public function getId();

    /**
     * Set the id
     * @param String $id
     * @return void
     */
    public function setId($id): void;

    /**
     * Get the created_at
     * @return DateTime
     */
    public function getCreated_at();

    /**
     * Set the created_at
     * @param DateTime $created_at
     * @return void
     */
    public function setCreated_at($created_at): void;

    /**
     * Get the updated_at
     * @return DateTime
     */
    public function getUpdated_at();

    /**
     * Set the updated_at
     * @param DateTime $updated_at
     * @return void
     */
    public function setUpdated_at($updated_at): void;

    /**
     * Get the is_active
     * @return Boolean
     */
    public function getIs_active();

    /**
     * Set the is_active
     * @param Boolean $is_active
     * @return void
     */
    public function setIs_active($is_active): void;

    /**
     * Get the modified_by
     * @return String|null
     */
    public function getModified_by();

    /**
     * Set the modified_by
     * @param String|null $modified_by
     * @return void
     */
    public function setModified_by($modified_by): void;

    /**
     * Get the name
     * @return String
     */
    public function getName();

    /**
     * Set the name
     * @param String $name
     * @return void
     */
    public function setName($name): void;

    /**
     * Get the email
     * @return String
     */
    public function getEmail();

    /**
     * Set the email
     * @param String $email
     * @return void
     */
    public function setEmail($email): void;

    /**
     * Get the organizationId
     * @return String
     */
    public function getOrganizationId();

    /**
     * Set the organizationId
     * @param String $organizationId
     * @return void
     */
    public function setOrganizationId($organizationId): void;

    /**
     * Get the organization
     * @return Organization
     */
    public function getOrganization();

    /**
     * Set the organization
     * @param Organization $organization
     * @return void
     */
    public function setOrganization($organization): void;

    /**
     * Get the contacts
     * @return Contact
     */
    public function getContacts();

    /**
     * Set the contacts
     * @param Contact $contacts
     * @return void
     */
    public function setContacts($contacts): void;

    /**
     * Get the packages
     * @return Package
     */
    public function getPackages();

    /**
     * Set the packages
     * @param Package $packages
     * @return void
     */
    public function setPackages($packages): void;

    /**
     * Get related organization
     * @return Organization
     */
    public function organization();

    /**
     * Get related contacts
     * @return Contact[]
     */
    public function contacts();

    /**
     * Get related packages
     * @return Package[]
     */
    public function packages();

}
