<?php

/**
 * This file is auto-generated by LorPHP.
 * Generated on: 2025-06-05 14:48:23
 * 
 * WARNING: Do not edit this file manually.
 * Any changes will be overwritten when the file is regenerated.
 */
namespace LorPHP\Interfaces;

/**
 * Interface PackageInterface
 * Represents a service package
 *
 * @property String $id Unique identifier for the record
 * @property DateTime $created_at Timestamp of when the record was created
 * @property DateTime $updated_at Timestamp of when the record was last updated
 * @property Boolean $is_active Whether the record is active
 * @property String|null $modified_by Identifier of the user who last modified the record
 * @property String $name Name
 * @property Client $clients Clients subscribed to this package
 */
interface PackageInterface
{
    /**
     * Get the id
     * @return String
     */
    public function getId();

    /**
     * Set the id
     * @param String $id
     * @return void
     */
    public function setId($id): void;

    /**
     * Get the created_at
     * @return DateTime
     */
    public function getCreated_at();

    /**
     * Set the created_at
     * @param DateTime $created_at
     * @return void
     */
    public function setCreated_at($created_at): void;

    /**
     * Get the updated_at
     * @return DateTime
     */
    public function getUpdated_at();

    /**
     * Set the updated_at
     * @param DateTime $updated_at
     * @return void
     */
    public function setUpdated_at($updated_at): void;

    /**
     * Get the is_active
     * @return Boolean
     */
    public function getIs_active();

    /**
     * Set the is_active
     * @param Boolean $is_active
     * @return void
     */
    public function setIs_active($is_active): void;

    /**
     * Get the modified_by
     * @return String|null
     */
    public function getModified_by();

    /**
     * Set the modified_by
     * @param String|null $modified_by
     * @return void
     */
    public function setModified_by($modified_by): void;

    /**
     * Get the name
     * @return String
     */
    public function getName();

    /**
     * Set the name
     * @param String $name
     * @return void
     */
    public function setName($name): void;

    /**
     * Get the clients
     * @return Client
     */
    public function getClients();

    /**
     * Set the clients
     * @param Client $clients
     * @return void
     */
    public function setClients($clients): void;

    /**
     * Get related clients
     * @return Client[]
     */
    public function clients();

}
