<?php

/**
 * This file is auto-generated by LorPHP.
 * Generated on: 2025-05-22 01:09:49
 * 
 * WARNING: Do not edit this file manually.
 * Any changes will be overwritten when the file is regenerated.
 */
namespace LorPHP\Interfaces;

/**
 * Interface PermissionInterface
 * Represents a permission that can be assigned to users/roles
 *
 * @property String $id Unique identifier for the record
 * @property DateTime $createdAt Timestamp of when the record was created
 * @property DateTime $updatedAt Timestamp of when the record was last updated
 * @property Boolean $isActive Whether the record is active
 * @property String|null $modifiedBy Identifier of the user who last modified the record
 * @property String $name Name
 * @property User $users Users who have this permission
 */
interface PermissionInterface
{
    /**
     * Get the id
     * @return String
     */
    public function getId();

    /**
     * Set the id
     * @param String $id
     * @return void
     */
    public function setId($id): void;

    /**
     * Get the createdAt
     * @return DateTime
     */
    public function getCreatedAt();

    /**
     * Set the createdAt
     * @param DateTime $createdAt
     * @return void
     */
    public function setCreatedAt($createdAt): void;

    /**
     * Get the updatedAt
     * @return DateTime
     */
    public function getUpdatedAt();

    /**
     * Set the updatedAt
     * @param DateTime $updatedAt
     * @return void
     */
    public function setUpdatedAt($updatedAt): void;

    /**
     * Get the isActive
     * @return Boolean
     */
    public function getIsActive();

    /**
     * Set the isActive
     * @param Boolean $isActive
     * @return void
     */
    public function setIsActive($isActive): void;

    /**
     * Get the modifiedBy
     * @return String|null
     */
    public function getModifiedBy();

    /**
     * Set the modifiedBy
     * @param String|null $modifiedBy
     * @return void
     */
    public function setModifiedBy($modifiedBy): void;

    /**
     * Get the name
     * @return String
     */
    public function getName();

    /**
     * Set the name
     * @param String $name
     * @return void
     */
    public function setName($name): void;

    /**
     * Get the users
     * @return User
     */
    public function getUsers();

    /**
     * Set the users
     * @param User $users
     * @return void
     */
    public function setUsers($users): void;

    /**
     * Get related users
     * @return User[]
     */
    public function users();

}
