<?php

/**
 * This file is auto-generated by LorPHP.
 * Generated on: 2025-05-23 20:40:25
 * 
 * WARNING: Do not edit this file manually.
 * Any changes will be overwritten when the file is regenerated.
 */
namespace LorPHP\Interfaces;

/**
 * Interface RateLimitInterface
 * Rate limiting records for API and sensitive endpoints
 *
 * @property String $id Unique identifier for the record
 * @property DateTime $created_at Timestamp of when the record was created
 * @property DateTime $updated_at Timestamp of when the record was last updated
 * @property Boolean $is_active Whether the record is active
 * @property String|null $modified_by Identifier of the user who last modified the record
 * @property String $ipAddress IP address of the client
 * @property String $endpoint The endpoint being rate limited
 * @property Integer $requests Number of requests in the current window
 * @property DateTime $windowStart When this rate limit window started
 * @property Integer $windowDuration Duration of rate limit window in seconds
 * @property Integer $maxRequests Maximum number of requests allowed in window
 * @property String|null $userId Associated user if authenticated
 * @property Boolean $blocked Whether requests are blocked for this IP/endpoint
 */
interface RateLimitInterface
{
    /**
     * Get the id
     * @return String
     */
    public function getId();

    /**
     * Set the id
     * @param String $id
     * @return void
     */
    public function setId($id): void;

    /**
     * Get the created_at
     * @return DateTime
     */
    public function getCreated_at();

    /**
     * Set the created_at
     * @param DateTime $created_at
     * @return void
     */
    public function setCreated_at($created_at): void;

    /**
     * Get the updated_at
     * @return DateTime
     */
    public function getUpdated_at();

    /**
     * Set the updated_at
     * @param DateTime $updated_at
     * @return void
     */
    public function setUpdated_at($updated_at): void;

    /**
     * Get the is_active
     * @return Boolean
     */
    public function getIs_active();

    /**
     * Set the is_active
     * @param Boolean $is_active
     * @return void
     */
    public function setIs_active($is_active): void;

    /**
     * Get the modified_by
     * @return String|null
     */
    public function getModified_by();

    /**
     * Set the modified_by
     * @param String|null $modified_by
     * @return void
     */
    public function setModified_by($modified_by): void;

    /**
     * Get the ipAddress
     * @return String
     */
    public function getIpAddress();

    /**
     * Set the ipAddress
     * @param String $ipAddress
     * @return void
     */
    public function setIpAddress($ipAddress): void;

    /**
     * Get the endpoint
     * @return String
     */
    public function getEndpoint();

    /**
     * Set the endpoint
     * @param String $endpoint
     * @return void
     */
    public function setEndpoint($endpoint): void;

    /**
     * Get the requests
     * @return Integer
     */
    public function getRequests();

    /**
     * Set the requests
     * @param Integer $requests
     * @return void
     */
    public function setRequests($requests): void;

    /**
     * Get the windowStart
     * @return DateTime
     */
    public function getWindowStart();

    /**
     * Set the windowStart
     * @param DateTime $windowStart
     * @return void
     */
    public function setWindowStart($windowStart): void;

    /**
     * Get the windowDuration
     * @return Integer
     */
    public function getWindowDuration();

    /**
     * Set the windowDuration
     * @param Integer $windowDuration
     * @return void
     */
    public function setWindowDuration($windowDuration): void;

    /**
     * Get the maxRequests
     * @return Integer
     */
    public function getMaxRequests();

    /**
     * Set the maxRequests
     * @param Integer $maxRequests
     * @return void
     */
    public function setMaxRequests($maxRequests): void;

    /**
     * Get the userId
     * @return String|null
     */
    public function getUserId();

    /**
     * Set the userId
     * @param String|null $userId
     * @return void
     */
    public function setUserId($userId): void;

    /**
     * Get the blocked
     * @return Boolean
     */
    public function getBlocked();

    /**
     * Set the blocked
     * @param Boolean $blocked
     * @return void
     */
    public function setBlocked($blocked): void;

}
