<?php

/**
 * This file is auto-generated by LorPHP.
 * Generated on: 2025-06-04 16:06:18
 * 
 * WARNING: Do not edit this file manually.
 * Any changes will be overwritten when the file is regenerated.
 */
namespace LorPHP\Interfaces;

/**
 * Interface UserInterface
 * Represents a user in the system
 *
 * @property String $id Unique identifier for the record
 * @property DateTime $created_at Timestamp of when the record was created
 * @property DateTime $updated_at Timestamp of when the record was last updated
 * @property Boolean $is_active Whether the record is active
 * @property String|null $modified_by Identifier of the user who last modified the record
 * @property String $name Name
 * @property String $email Email
 * @property String $password Password
 * @property String|null $role_id Role id
 * @property String $organization_id Organization id
 * @property Role $role The role of this user
 * @property Organization $organization The organization this user belongs to
 * @property Client $clients Clients associated with this user
 */
interface UserInterface
{
    /**
     * Get the id
     * @return String
     */
    public function getId();

    /**
     * Set the id
     * @param String $id
     * @return void
     */
    public function setId($id): void;

    /**
     * Get the created_at
     * @return DateTime
     */
    public function getCreated_at();

    /**
     * Set the created_at
     * @param DateTime $created_at
     * @return void
     */
    public function setCreated_at($created_at): void;

    /**
     * Get the updated_at
     * @return DateTime
     */
    public function getUpdated_at();

    /**
     * Set the updated_at
     * @param DateTime $updated_at
     * @return void
     */
    public function setUpdated_at($updated_at): void;

    /**
     * Get the is_active
     * @return Boolean
     */
    public function getIs_active();

    /**
     * Set the is_active
     * @param Boolean $is_active
     * @return void
     */
    public function setIs_active($is_active): void;

    /**
     * Get the modified_by
     * @return String|null
     */
    public function getModified_by();

    /**
     * Set the modified_by
     * @param String|null $modified_by
     * @return void
     */
    public function setModified_by($modified_by): void;

    /**
     * Get the name
     * @return String
     */
    public function getName();

    /**
     * Set the name
     * @param String $name
     * @return void
     */
    public function setName($name): void;

    /**
     * Get the email
     * @return String
     */
    public function getEmail();

    /**
     * Set the email
     * @param String $email
     * @return void
     */
    public function setEmail($email): void;

    /**
     * Get the password
     * @return String
     */
    public function getPassword();

    /**
     * Set the password
     * @param String $password
     * @return void
     */
    public function setPassword($password): void;

    /**
     * Get the role_id
     * @return String|null
     */
    public function getRole_id();

    /**
     * Set the role_id
     * @param String|null $role_id
     * @return void
     */
    public function setRole_id($role_id): void;

    /**
     * Get the organization_id
     * @return String
     */
    public function getOrganization_id();

    /**
     * Set the organization_id
     * @param String $organization_id
     * @return void
     */
    public function setOrganization_id($organization_id): void;

    /**
     * Get the role
     * @return Role
     */
    public function getRole();

    /**
     * Set the role
     * @param Role $role
     * @return void
     */
    public function setRole($role): void;

    /**
     * Get the organization
     * @return Organization
     */
    public function getOrganization();

    /**
     * Set the organization
     * @param Organization $organization
     * @return void
     */
    public function setOrganization($organization): void;

    /**
     * Get the clients
     * @return Client
     */
    public function getClients();

    /**
     * Set the clients
     * @param Client $clients
     * @return void
     */
    public function setClients($clients): void;

    /**
     * Get related role
     * @return Role
     */
    public function role();

    /**
     * Get related organization
     * @return Organization
     */
    public function organization();

    /**
     * Get related clients
     * @return Client[]
     */
    public function clients();

}
