<?php

/**
 * This file is auto-generated by LorPHP.
 * Generated on: 2025-06-04 15:58:32
 * 
 * WARNING: Do not edit this file manually.
 * Any changes will be overwritten when the file is regenerated.
 */
namespace LorPHP\Models;

use LorPHP\Core\Model;
use LorPHP\Interfaces\ClientInterface;
use LorPHP\Models\Organization;
use LorPHP\Models\Contact;
use LorPHP\Models\Package;

/**
 * Class Client
 * Represents the Client entity.
 *
 * @property string $id
 * @property string $created_at
 * @property string $updated_at
 * @property bool $is_active
 * @property string $modified_by
 * @property string $name
 * @property string $email
 * @property string $organizationId
 */
class Client extends Model implements ClientInterface
{
    protected static string $tableName = 'clients';
    protected static $fillable = ['id', 'id', 'created_at', 'created_at', 'updated_at', 'updated_at', 'is_active', 'is_active', 'modified_by', 'modified_by', 'name', 'name', 'email', 'email', 'organizationId', 'organization_id', 'organization', 'organization', 'contacts', 'contacts', 'packages', 'packages'];
                
                
    /**
     * Find a record by its email
     * @param string $email The email to search for
     * @return static|null The record if found, null otherwise
     */
    public static function findByEmail(string $email): ?static
    {
        $db = \LorPHP\Core\Database::getInstance();
        $data = $db->findOne(static::$tableName, ['email' => $email]);
        
        if ($data) {
            $model = new static();
            $model->fill($data);
            return $model;
        }
        
        return null;
    }
                
    /**
     * Get related organization
     * @return Organization[]
     */
    public function organization(): ?\LorPHP\Core\Model
    {
        return $this->belongsTo(Organization::class);
    }
                
    public function getOrganization()
    {
        return $this->organization();
    }

    public function setOrganization($organization): void
    {
        $this->organization = $organization;
    }
                
    /**
     * Get related contacts
     * @return Contact[]
     */
    public function contacts(): array
    {
        return $this->hasMany(Contact::class);
    }
                
    public function getContacts()
    {
        return $this->contacts();
    }

    public function setContacts($contacts): void
    {
        $this->contacts = $contacts;
    }
                
    /**
     * Get related packages
     * @return Package[]
     */
    public function packages(): array
    {
        return $this->manyToMany(Package::class);
    }
                
    public function getPackages()
    {
        return $this->packages();
    }

    public function setPackages($packages): void
    {
        $this->packages = $packages;
    }
                
    public function getId()
    {
        return $this->id;
    }

    public function setId($id): void
    {
        $this->id = $id;
    }
                
    public function getCreated_at()
    {
        return $this->created_at;
    }

    public function setCreated_at($created_at): void
    {
        $this->created_at = $created_at;
    }
                
    public function getUpdated_at()
    {
        return $this->updated_at;
    }

    public function setUpdated_at($updated_at): void
    {
        $this->updated_at = $updated_at;
    }
                
    public function getIs_active()
    {
        return $this->is_active;
    }

    public function setIs_active($is_active): void
    {
        $this->is_active = $is_active;
    }
                
    public function getModified_by()
    {
        return $this->modified_by;
    }

    public function setModified_by($modified_by): void
    {
        $this->modified_by = $modified_by;
    }
                
    public function getName()
    {
        return $this->name;
    }

    public function setName($name): void
    {
        $this->name = $name;
    }
                
    public function getEmail()
    {
        return $this->email;
    }

    public function setEmail($email): void
    {
        $this->email = $email;
    }
                
    public function getOrganizationId()
    {
        return $this->organizationId;
    }

    public function setOrganizationId($organization_id): void
    {
        $this->organizationId = $organization_id;
    }
                
    public function getOrganizationId()
    {
        return $this->organizationId;
    }

    public function setOrganizationId($organizationId): void
    {
        $this->organizationId = $organizationId;
    }


    public function save(): bool {
        return parent::save();
    }}
