<?php

/**
 * This file is auto-generated by LorPHP.
 * Generated on: 2025-05-22 01:28:30
 * 
 * WARNING: Do not edit this file manually.
 * Any changes will be overwritten when the file is regenerated.
 */
namespace LorPHP\Models;

use LorPHP\Core\Model;
use LorPHP\Interfaces\ContactInterface;
use LorPHP\Models\Client;

/**
 * Class Contact
 * Represents the Contact entity.
 *
 * @property string $id
 * @property string $createdAt
 * @property string $updatedAt
 * @property bool $isActive
 * @property string $modifiedBy
 * @property string $name
 * @property string $email
 * @property string $clientId
 */
class Contact extends Model implements ContactInterface
{
    protected static string $tableName = 'contacts';
    protected static $fillable = ['id', 'createdAt', 'updatedAt', 'isActive', 'modifiedBy', 'name', 'email', 'clientId', 'client'];
                

                
    /**
     * Get related client
     * @return Client[]
     */
    public function client()
    {
        return $this->belongsTo(Client::class);
    }
                
    public function getClient()
    {
        return $this->client();
    }

    public function setClient($client): void
    {
        $this->client = $client;
    }
                
    public function getId()
    {
        return $this->id;
    }

    public function setId($id): void
    {
        $this->id = $id;
    }
                
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    public function setCreatedAt($createdAt): void
    {
        $this->createdAt = $createdAt;
    }
                
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt($updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }
                
    public function getIsActive()
    {
        return $this->isActive;
    }

    public function setIsActive($isActive): void
    {
        $this->isActive = $isActive;
    }
                
    public function getModifiedBy()
    {
        return $this->modifiedBy;
    }

    public function setModifiedBy($modifiedBy): void
    {
        $this->modifiedBy = $modifiedBy;
    }
                
    public function getName()
    {
        return $this->name;
    }

    public function setName($name): void
    {
        $this->name = $name;
    }
                
    public function getEmail()
    {
        return $this->email;
    }

    public function setEmail($email): void
    {
        $this->email = $email;
    }
                
    public function getClientId()
    {
        return $this->clientId;
    }

    public function setClientId($clientId): void
    {
        $this->clientId = $clientId;
    }}
