<?php

/**
 * This file is auto-generated by LorPHP.
 * Generated on: 2025-06-04 15:58:33
 * 
 * WARNING: Do not edit this file manually.
 * Any changes will be overwritten when the file is regenerated.
 */
namespace LorPHP\Models;

use LorPHP\Core\Model;
use LorPHP\Interfaces\ContactInterface;
use LorPHP\Models\Client;

/**
 * Class Contact
 * Represents the Contact entity.
 *
 * @property string $id
 * @property string $created_at
 * @property string $updated_at
 * @property bool $is_active
 * @property string $modified_by
 * @property string $name
 * @property string $email
 * @property string $clientId
 */
class Contact extends Model implements ContactInterface
{
    protected static string $tableName = 'contacts';
    protected static $fillable = ['id', 'id', 'created_at', 'created_at', 'updated_at', 'updated_at', 'is_active', 'is_active', 'modified_by', 'modified_by', 'name', 'name', 'email', 'email', 'clientId', 'client_id', 'client', 'client'];
                

                
    /**
     * Get related client
     * @return Client[]
     */
    public function client(): ?\LorPHP\Core\Model
    {
        return $this->belongsTo(Client::class);
    }
                
    public function getClient()
    {
        return $this->client();
    }

    public function setClient($client): void
    {
        $this->client = $client;
    }
                
    public function getId()
    {
        return $this->id;
    }

    public function setId($id): void
    {
        $this->id = $id;
    }
                
    public function getCreated_at()
    {
        return $this->created_at;
    }

    public function setCreated_at($created_at): void
    {
        $this->created_at = $created_at;
    }
                
    public function getUpdated_at()
    {
        return $this->updated_at;
    }

    public function setUpdated_at($updated_at): void
    {
        $this->updated_at = $updated_at;
    }
                
    public function getIs_active()
    {
        return $this->is_active;
    }

    public function setIs_active($is_active): void
    {
        $this->is_active = $is_active;
    }
                
    public function getModified_by()
    {
        return $this->modified_by;
    }

    public function setModified_by($modified_by): void
    {
        $this->modified_by = $modified_by;
    }
                
    public function getName()
    {
        return $this->name;
    }

    public function setName($name): void
    {
        $this->name = $name;
    }
                
    public function getEmail()
    {
        return $this->email;
    }

    public function setEmail($email): void
    {
        $this->email = $email;
    }
                
    public function getClientId()
    {
        return $this->clientId;
    }

    public function setClientId($client_id): void
    {
        $this->clientId = $client_id;
    }
                
    public function getClientId()
    {
        return $this->clientId;
    }

    public function setClientId($clientId): void
    {
        $this->clientId = $clientId;
    }


    public function save(): bool {
        return parent::save();
    }}
