<?php

/**
 * This file is auto-generated by LorPHP.
 * Generated on: 2025-05-22 01:28:30
 * 
 * WARNING: Do not edit this file manually.
 * Any changes will be overwritten when the file is regenerated.
 */
namespace LorPHP\Models;

use LorPHP\Core\Model;
use LorPHP\Interfaces\OrganizationInterface;
use LorPHP\Models\User;
use LorPHP\Models\Client;

/**
 * Class Organization
 * Represents the Organization entity.
 *
 * @property string $id
 * @property string $createdAt
 * @property string $updatedAt
 * @property bool $isActive
 * @property string $modifiedBy
 * @property string $name
 */
class Organization extends Model implements OrganizationInterface
{
    protected static string $tableName = 'organizations';
    protected static $fillable = ['id', 'createdAt', 'updatedAt', 'isActive', 'modifiedBy', 'name', 'users', 'clients'];
                

                
    /**
     * Get related users
     * @return User[]
     */
    public function users()
    {
        return $this->hasMany(User::class);
    }
                
    public function getUsers()
    {
        return $this->users();
    }

    public function setUsers($users): void
    {
        $this->users = $users;
    }
                
    /**
     * Get related clients
     * @return Client[]
     */
    public function clients()
    {
        return $this->hasMany(Client::class);
    }
                
    public function getClients()
    {
        return $this->clients();
    }

    public function setClients($clients): void
    {
        $this->clients = $clients;
    }
                
    public function getId()
    {
        return $this->id;
    }

    public function setId($id): void
    {
        $this->id = $id;
    }
                
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    public function setCreatedAt($createdAt): void
    {
        $this->createdAt = $createdAt;
    }
                
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt($updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }
                
    public function getIsActive()
    {
        return $this->isActive;
    }

    public function setIsActive($isActive): void
    {
        $this->isActive = $isActive;
    }
                
    public function getModifiedBy()
    {
        return $this->modifiedBy;
    }

    public function setModifiedBy($modifiedBy): void
    {
        $this->modifiedBy = $modifiedBy;
    }
                
    public function getName()
    {
        return $this->name;
    }

    public function setName($name): void
    {
        $this->name = $name;
    }}
