<?php

/**
 * This file is auto-generated by LorPHP.
 * Generated on: 2025-05-22 01:28:30
 * 
 * WARNING: Do not edit this file manually.
 * Any changes will be overwritten when the file is regenerated.
 */
namespace LorPHP\Models;

use LorPHP\Core\Model;
use LorPHP\Interfaces\PermissionInterface;
use LorPHP\Models\User;

/**
 * Class Permission
 * Represents the Permission entity.
 *
 * @property string $id
 * @property string $createdAt
 * @property string $updatedAt
 * @property bool $isActive
 * @property string $modifiedBy
 * @property string $name
 */
class Permission extends Model implements PermissionInterface
{
    protected static string $tableName = 'permissions';
    protected static $fillable = ['id', 'createdAt', 'updatedAt', 'isActive', 'modifiedBy', 'name', 'users'];
                
                
    /**
     * Find a record by its name
     * @param string $name The name to search for
     * @return static|null The record if found, null otherwise
     */
    public static function findByName(string $name): ?static
    {
        $db = \LorPHP\Core\Database::getInstance();
        $data = $db->findOne(static::$tableName, ['name' => $name]);
        
        if ($data) {
            $model = new static();
            $model->fill($data);
            return $model;
        }
        
        return null;
    }
                
    /**
     * Get related users
     * @return User[]
     */
    public function users()
    {
        return $this->manyToMany(User::class);
    }
                
    public function getUsers()
    {
        return $this->users();
    }

    public function setUsers($users): void
    {
        $this->users = $users;
    }
                
    public function getId()
    {
        return $this->id;
    }

    public function setId($id): void
    {
        $this->id = $id;
    }
                
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    public function setCreatedAt($createdAt): void
    {
        $this->createdAt = $createdAt;
    }
                
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt($updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }
                
    public function getIsActive()
    {
        return $this->isActive;
    }

    public function setIsActive($isActive): void
    {
        $this->isActive = $isActive;
    }
                
    public function getModifiedBy()
    {
        return $this->modifiedBy;
    }

    public function setModifiedBy($modifiedBy): void
    {
        $this->modifiedBy = $modifiedBy;
    }
                
    public function getName()
    {
        return $this->name;
    }

    public function setName($name): void
    {
        $this->name = $name;
    }}
