<?php

/**
 * This file is auto-generated by LorPHP.
 * Generated on: 2025-05-23 20:36:53
 * 
 * WARNING: Do not edit this file manually.
 * Any changes will be overwritten when the file is regenerated.
 */
namespace LorPHP\Models;

use LorPHP\Core\Model;
use LorPHP\Interfaces\RateLimitInterface;

/**
 * Class RateLimit
 * Represents the RateLimit entity.
 *
 * @property string $id
 * @property string $created_at
 * @property string $updated_at
 * @property bool $is_active
 * @property string $modified_by
 * @property string $ipAddress
 * @property string $endpoint
 * @property int $requests
 * @property string $windowStart
 * @property int $windowDuration
 * @property int $maxRequests
 * @property string $userId
 * @property bool $blocked
 */
class RateLimit extends Model implements RateLimitInterface
{
    protected static string $tableName = 'ratelimits';
    protected static $fillable = ['id', 'id', 'created_at', 'created_at', 'updated_at', 'updated_at', 'is_active', 'is_active', 'modified_by', 'modified_by', 'ipAddress', 'ip_address', 'endpoint', 'endpoint', 'requests', 'requests', 'windowStart', 'window_start', 'windowDuration', 'window_duration', 'maxRequests', 'max_requests', 'userId', 'user_id', 'blocked', 'blocked'];
                


                
    public function getId()
    {
        return $this->id;
    }

    public function setId($id): void
    {
        $this->id = $id;
    }
                
    public function getCreated_at()
    {
        return $this->created_at;
    }

    public function setCreated_at($created_at): void
    {
        $this->created_at = $created_at;
    }
                
    public function getUpdated_at()
    {
        return $this->updated_at;
    }

    public function setUpdated_at($updated_at): void
    {
        $this->updated_at = $updated_at;
    }
                
    public function getIs_active()
    {
        return $this->is_active;
    }

    public function setIs_active($is_active): void
    {
        $this->is_active = $is_active;
    }
                
    public function getModified_by()
    {
        return $this->modified_by;
    }

    public function setModified_by($modified_by): void
    {
        $this->modified_by = $modified_by;
    }
                
    public function getIpAddress()
    {
        return $this->ipAddress;
    }

    public function setIpAddress($ip_address): void
    {
        $this->ipAddress = $ip_address;
    }
                
    public function getIpAddress()
    {
        return $this->ipAddress;
    }

    public function setIpAddress($ipAddress): void
    {
        $this->ipAddress = $ipAddress;
    }
                
    public function getEndpoint()
    {
        return $this->endpoint;
    }

    public function setEndpoint($endpoint): void
    {
        $this->endpoint = $endpoint;
    }
                
    public function getRequests()
    {
        return $this->requests;
    }

    public function setRequests($requests): void
    {
        $this->requests = $requests;
    }
                
    public function getWindowStart()
    {
        return $this->windowStart;
    }

    public function setWindowStart($window_start): void
    {
        $this->windowStart = $window_start;
    }
                
    public function getWindowStart()
    {
        return $this->windowStart;
    }

    public function setWindowStart($windowStart): void
    {
        $this->windowStart = $windowStart;
    }
                
    public function getWindowDuration()
    {
        return $this->windowDuration;
    }

    public function setWindowDuration($window_duration): void
    {
        $this->windowDuration = $window_duration;
    }
                
    public function getWindowDuration()
    {
        return $this->windowDuration;
    }

    public function setWindowDuration($windowDuration): void
    {
        $this->windowDuration = $windowDuration;
    }
                
    public function getMaxRequests()
    {
        return $this->maxRequests;
    }

    public function setMaxRequests($max_requests): void
    {
        $this->maxRequests = $max_requests;
    }
                
    public function getMaxRequests()
    {
        return $this->maxRequests;
    }

    public function setMaxRequests($maxRequests): void
    {
        $this->maxRequests = $maxRequests;
    }
                
    public function getUserId()
    {
        return $this->userId;
    }

    public function setUserId($user_id): void
    {
        $this->userId = $user_id;
    }
                
    public function getUserId()
    {
        return $this->userId;
    }

    public function setUserId($userId): void
    {
        $this->userId = $userId;
    }
                
    public function getBlocked()
    {
        return $this->blocked;
    }

    public function setBlocked($blocked): void
    {
        $this->blocked = $blocked;
    }


    public function save(): bool {
        return parent::save();
    }}
